const COLORS = {
    temperature: [{
        min: -99,
        max: 5,
        col: "#3288bd"
    }, {
        min: 5,
        max: 15,
        col: "#66c2a5"
    }, {
        min: 15,
        max: 17.5,
        col: "#abdda4"
    }, {
        min: 17.5,
        max: 20,
        col: "#e6f598"
    }, {
        min: 20,
        max: 22.5,
        col: "#ffffbf"
    }, {
        min: 22.5,
        max: 25,
        col: "#fee08b"
    }, {
        min: 25,
        max: 27.5,
        col: "#fdae61"
    }, {
        min: 27.5,
        max: 30,
        col: "#f46d43"
    }, {
        min: 30,
        max: 99,
        col: "#d53e4f"
    }]
}